# Generated by Django 5.1.5 on 2025-02-05 11:27

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_category_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(default=0, null=True)),
                ('discount', models.PositiveIntegerField(default=0, null=True)),
                ('feature_image', models.CharField(max_length=255, null=True)),
                ('brand', models.CharField(max_length=255, null=True)),
                ('total', models.PositiveIntegerField(default=0, null=True)),
                ('available', models.PositiveIntegerField(default=0, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(blank=True, max_length=555, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='User.category')),
            ],
        ),
    ]
