# Generated by Django 5.1.5 on 2025-02-05 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=555, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.product')),
            ],
        ),
    ]
