# Generated by Django 5.1.5 on 2025-02-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
