# Generated by Django 4.2.16 on 2024-10-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_admin_delete_admin_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('mark', models.IntegerField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='imagess/')),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
