# Generated by Django 4.2.16 on 2024-10-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_student_delete_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mark',
            field=models.IntegerField(),
        ),
    ]
