# Generated by Django 4.2.16 on 2024-10-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0004_alter_student_image_alter_student_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='images/image.png', null=True, upload_to='images/'),
        ),
    ]
